---
 - name: jsnapy
   hosts: all
   connection: local
   gather_facts: no
   roles:
   - Juniper.junos

   tasks:

   - name: Collect Pre Snapshot
     junos_jsnapy:
       host: "{{ ansible_host }}"
       user: "{{ credentials.username }}"
       passwd: "{{ credentials.password }}"
       action: "snap_pre"
       test_files: /jsnapy/testfiles/test_file_check_lldp_states.yml

   - name: Collect Post Snapshot
     junos_jsnapy:
       host: "{{ ansible_host }}"
       user: "{{ credentials.username }}"
       passwd: "{{ credentials.password }}"
       action: "snap_post"
       test_files: /jsnapy/testfiles/test_file_check_lldp_states.yml

   - name: Compare snapshots
     junos_jsnapy:
       host: "{{ ansible_host }}"
       user: "{{ credentials.username }}"
       passwd: "{{ credentials.password }}"
       action: "check"
       test_files: /jsnapy/testfiles/test_file_check_lldp_states.yml
     register: test_check

   - name: Debug jsnapy
     debug: 
       msg: "{{ test_check }}"

   - name: Check JSNAPy tests results
     assert:
       that:
       - "test_check.passPercentage == 100"
       msg: "jsnapy test on {{ inventory_hostname }} failed"